services:
  - name: information-retrieval-service
    type: web
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000